config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  resources :users
  resources :listings do
    resources :bids, only: [:create]
    resources :braintree, only: [:new, :create]
  end
  resources :images, only: [:destroy]
  resources :bids, except: [:create]
  get '/search', to: 'listings#search', as: 'search'
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :images, :dependent => :destroy
  has_many :bids, :dependent => :destroy
  belongs_to :user
  searchkick match: :word_start, searchable: [:state, :city, :address, :name]
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, only: [:index]
  before_action :authorize_check, only: [:update, :destroy]
  before_filter :authorize, except: [:new, :create]

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save
      if params[:images]
        params[:images].each do |image|
          @listing.images.create(image: image)
        end
      end
      redirect_to @listing, notice: "Listing created!"
    else
      redirect_to '/', notice: "Failed to create!"
    end
  end

  def index
    @listings = Listing.all.order("created_at DESC")
  end

  def search
    @listings = Listing.search(params[:term], fields: ["state", "city", "address", "name"], misspellings: {below: 5})#.paginate(:page => params[:page]).per_page(20)
    if @listings.blank?
      redirect_to root_path, notice: "No results found!"
    else
      render :search
    end
  end

  def show
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      if params[:images]
        @listing.images.destroy_all
        params[:images].each do |image|
          @listing.images.create(image: image)
        end
      end
      redirect_to @listing, notice: 'Listing was successfully updated.'
    else
      redirect_to @listing, notice: 'Failed to update listing.'
    end
  end

  def destroy
    @listing.destroy
    redirect_to listings_url, notice: 'Listing was successfully destroyed.'
  end

  def expired_listing
    if @listing.expiration < DateTime.now
      @listing.expired = true
      if !@listing.bids.empty?
        @listing.sold = true
      end
      @listing.save
    end
  end

  private
  def set_listing
    @listing = Listing.find(params[:id])
  end

  def authorize_check
    if @user != current_user && !current_user.admin?
      redirect_to root_path
    end
  end

  def listing_params
      params.require(:listing).permit(:name, :address, :city, :state, :house_type, :num_of_rooms, :price, :expiration, :user_id, images_attributes: [:image, :listing_id])
  end

  def admin_only
    redirect_to sign_in_path unless current_user.admin?
  end
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/listings/_container.html.erb
<div id = "big_container">
<% if !@listing.bids.empty? %>
  <h1> CURRENT HIGHEST BID IS RM<%= @listing.bids.find_by(chosen_bid: true).bidding_price  %></h1>
<% else %>
  <h1> THERE IS NO BID AT THE MOMENT! BE THE FIRST BIDDER! </h1>
<% end %>

<br>
  <% if @listing.user_id != current_user.id %>
    <% if @bid != nil %>
      <% if @bid.user_id != current_user.id %>
      <h1> BID NOW! </h1>
        <%= render 'bids/form' %>
      <% else %>
      <h1> YOU ARE THE CURRENT HIGHEST BIDDER! </h1>
      <% end %>
    <% else %>
    <h1> BID NOW! </h1>
      <%= render 'bids/form' %>
    <% end %>
  <% end %>
</div>

app/views/listings/edit.html.erb
<div class = "container col-md-offset-4 col-md-4 col-md-offset-4">
<h1>Edit Listing</h1><br>

<%= form_for(@listing, :html => { multipart: true }) do |f| %>

  Name: <%= f.text_field :name %><br><br>
  Type: <%= f.select :house_type, ['Bungalow', 'Single Terrace', 'Double Terrace', 'Condominium', 'Apartment', 'Semi D'] %><br><br>
  Address: <%= f.text_field :address %><br><br>
  City: <%= f.text_field :city %><br><br>
  State: <%= f.select :state, ['Kuala Lumpur', 'Selangor', 'Perak', 'Melaka', 'Negeri Sembilan', 'Pahang', 'Johor', 'Kedah', 'Pulau Pinang', 'Perlis', 'Kelantan', 'Terengganu', 'Sarawak', 'Sabah'] %><br><br>
  Number Of Rooms: <%= f.number_field :num_of_rooms %><br><br>
  Starting Price: RM <%= f.number_field :price %><br><br>
  Expiration Date:  <div class="container">
                      <div class="row">
                          <div class='col-sm-4'>
                              <div class="form-group">
                                  <div class='input-group date' id='datetimepicker5'>
                                      <%= f.text_field :expiration, class: 'form-control' %>
                                      <span class="input-group-addon">
                                          <span class="glyphicon glyphicon-calendar"></span>
                                      </span>
                                  </div>
                              </div>
                          </div>
                          <script type="text/javascript">
                              $(function () {
                                  $('#datetimepicker5').datetimepicker({
                                      minDate: moment(),
                                  });
                              });
                          </script>
                      </div>
                  </div>

                  <%= f.fields_for :image do |ff| %>
                      <div class="field" id='uploadavatar'>
                        <%= ff.label :image %><br>
                        <%= ff.file_field :image, multiple: true, name: "images[]" %>
                      </div>
                    <% end %>
                    <br><br>
  <%= f.submit "Update" %>

<% end %>
</div>

app/views/listings/index.html.erb
<div class = "container col-md-offset-1 col-md-10 col-md-offset-1">
<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Listing Name</th>
      <th>Type</th>
      <th>Number Of Rooms</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Starting Price</th>
      <th>Expiration</th>
      <th>Expired?</th>
      <th>Sold?</th>
      <th>Paid?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= listing.house_type %></td>
        <td><%= listing.num_of_rooms %></td>
        <td><%= listing.address %></td>
        <td><%= listing.city %></td>
        <td><%= listing.state %></td>
        <td><%= listing.price %></td>
        <td><%= listing.expiration %></td>
        <td><%= listing.expired %></td>
        <td><%= listing.sold %></td>
        <td><%= listing.paid %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/listings/new.html.erb
<div class = "container col-md-offset-4 col-md-4 col-md-offset-4">
<h1>New Listing</h1><br>

<%= form_for(@listing, :html => { multipart: true }) do |f| %>

  Name: <%= f.text_field :name %><br><br>
  Type: <%= f.select :house_type, ['Bungalow', 'Single Terrace', 'Double Terrace', 'Condominium', 'Apartment', 'Semi D'] %><br><br>
  Address: <%= f.text_field :address %><br><br>
  City: <%= f.text_field :city %><br><br>
  State: <%= f.select :state, ['Kuala Lumpur', 'Selangor', 'Perak', 'Melaka', 'Negeri Sembilan', 'Pahang', 'Johor', 'Kedah', 'Pulau Pinang', 'Perlis', 'Kelantan', 'Terengganu', 'Sarawak', 'Sabah'] %><br><br>
  Number Of Rooms: <%= f.number_field :num_of_rooms %><br><br>
  Starting Price: RM <%= f.number_field :price %><br><br>
  Expiration Date:  <div class="container">
                      <div class="row">
                          <div class='col-sm-4'>
                              <div class="form-group">
                                  <div class='input-group date' id='datetimepicker5'>
                                      <%= f.text_field :expiration, class: 'form-control' %>
                                      <span class="input-group-addon">
                                          <span class="glyphicon glyphicon-calendar"></span>
                                      </span>
                                  </div>
                              </div>
                          </div>
                          <script type="text/javascript">
                              $(function () {
                                  $('#datetimepicker5').datetimepicker({
                                      minDate: moment(),
                                  });
                              });
                          </script>
                      </div>
                  </div>

                  <%= f.fields_for :image do |ff| %>
                      <div class="field" id='uploadavatar'>
                        <%= ff.label :image %><br>
                        <%= ff.file_field :image, multiple: true, name: "images[]" %>
                      </div>
                    <% end %>
                    <br><br>
  <%= f.submit "Create" %>

<% end %>
</div>

app/views/listings/search.html.erb
<h1>Search Results:</h1>
<br>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% @listings.each do |listing| %>
    <div class="responsive">
      <div class="gallery">
        <% if !listing.images.empty? %>
        <%= link_to image_tag(listing.images.first.image.thumb.url), listing%>
        <% end %>
        <div class="desc">RM<%= listing.price %> <%= listing.name %> <%= listing.address%></div>
      </div>
    </div>
   <% end %>
  </div>
</div>

app/views/listings/show.html.erb
<div class = "container">
  <h1><%= @listing.name %></h1><br>

  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <% @listing.images.each_with_index do |i, ind| %>
            <% if ind == 0 %>
              <div class="item active">
                <%= image_tag i.image.url, style:"width: 100%" %>
              </div>
            <% else %>
              <div class="item">
                <%= image_tag i.image.url, style:"width: 100%" %>
              </div>
            <% end %>
          <% end %>
        </div>
        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
<div class = "container col-md-offset-3 col-md-6 col-md-offset-3">
<br>
<p>
  <strong>Type:</strong>
  <%= @listing.house_type %>
</p>

<p>
  <strong>Number Of Rooms:</strong>
  <%= @listing.num_of_rooms %>
</p>

<p>
  <strong>Address</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @listing.state %>
</p>

<p>
  <strong>Starting Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @listing.expiration %>
</p>

<br>
<%= render 'listings/container' %>

<h3>Bids:</h3>
<br>
  <table id = "bid_table">
    <tr>
      <th>User Name</th>
      <th>Bidding Price</th>
      <th>Highest Bid</th>
      <th></th>
    </tr>
    <% @listing.bids.order("bidding_price DESC").each do |bid| %>
    <tr>
    <% if bid.id != nil %>
    <td><%= bid.user.username %></td>
    <td><%= bid.bidding_price %></td>
    <td><%= bid.chosen_bid %></td>
    <% if current_user.role == "admin" %>
    <td><%= link_to "Delete Bid", bid, method: :delete %></td>
    <% end %>
    </tr>
  <% end %>
  <% end %>
  </table>
  <br>
  <% if current_user.role == "admin" %>
  <%= link_to "Edit", edit_listing_path %>
  <% end %>
</div>
</div>