config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  resources :users
  resources :listings do
    resources :bids, only: [:create]
    resources :braintree, only: [:new, :create]
  end
  resources :images, only: [:destroy]
  resources :bids, except: [:create]
  get '/search', to: 'listings#search', as: 'search'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :authentications, dependent: :destroy
  has_many :listings, :dependent => :destroy
  has_many :bids, :dependent => :destroy
  has_secure_password
  validates :first_name, presence:true
  validates :last_name, presence:true
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, message: "Not a valid email!" }
  validates :password, format:{ with: /(?=.*\d)(?=.*([a-z]|[A-Z]))([\x20-\x7E]){8,40}/, message: "Password does not meet requirements!"}
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  mount_uploader :avatar, AvatarUploader


  def self.create_with_auth_and_hash(authentication, auth_hash)
      user = self.create!(
        username: auth_hash["name"],
        email: auth_hash["extra"]["raw_info"]["email"],
        password: SecureRandom.hex(4)
      )
      user.authentications << authentication
      return user
  end

    # grab fb_token to access Facebook for user data
  def fb_token
      x = self.authentications.find_by(provider: 'facebook')
      return x.token
      unless x.nil?
  end
end

  def set_default_role
    self.role = :user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, only: [:index]
  before_action :authorize_check, only: [:update, :destroy]
  before_filter :authorize, except: [:new, :create]

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup', notice: "Failed to sign up!"
    end
  end

  def index
    @users = User.all.order("created_at DESC")
  end

  def show
    @bids = current_user.bids.all
    listing_ids = current_user.bids.where(chosen_bid: true).pluck(:listing_id)
    @listings = Listing.where(id: listing_ids)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      redirect_to @user, notice: 'Failed to update.'
    end
  end

  def destroy
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def authorize_check
    if @user != current_user && !current_user.admin?
      redirect_to root_path
    end
  end

  def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :avatar)
  end

  def admin_only
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class = "container col-md-offset-4 col-md-4 col-md-offset-4">
<h1>Edit User</h1><br>

<%= form_for @user do |f| %>
  <p><%= f.file_field :avatar, id:"uploadavatar" %></p>
  First Name: <%= f.text_field :first_name %><br><br>
  Last Name: <%= f.text_field :last_name %><br><br>
  Username: <%= f.text_field :username %><br><br>
  Email: <%= f.email_field :email %><br><br>
  Password: <%= f.password_field :password %><br><br>

  <%= f.submit "Update" %><br><br>

<% end %>
</div>

app/views/users/index.html.erb
<div class = "container col-md-offset-1 col-md-10 col-md-offset-1">
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %> <%= user.last_name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/users/new.html.erb
<br><br><br>
<div class = "container col-md-offset-4 col-md-4 col-md-offset-4">
<h1>Signup!</h1><br>

<%= form_for :user, url: '/users' do |f| %>

  First Name: <%= f.text_field :first_name %><br><br>
  Last Name: <%= f.text_field :last_name %><br><br>
  Username: <%= f.text_field :username %><br><br>
  Email: <%= f.email_field :email %><br><br>
  Password: <%= f.password_field :password %><br><br>

  <%= f.submit "Continue" %><br><br>

  or <%= link_to "Sign in with Facebook", "/auth/facebook" %>
<% end %>
</div>

app/views/users/show.html.erb
<div class = "container col-md-offset-3 col-md-6 col-md-offset-3">
<h1>Profile</h1><br>

<% if current_user.avatar.url != nil%>
<%= image_tag(current_user.avatar.url, :class =>'img-circle') %>
<% end %>
<br><br>

<p>
  <strong>Name:</strong>
  <%= @user.first_name %> <%= @user.last_name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<% if current_user.id = @user.id %>
<%= link_to 'Edit', edit_user_path(@user) %>
<% end %>
<br><br>

<h2>Bids</h2>
<br>
<table>
  <tr>
    <th>Listing Name</th>
    <th>Bidding Price</th>
    <th>Winning Bid?</th>
  </tr>
<% @bids.each do |bid| %>
<tr>
  <td><%= link_to bid.listing.name, bid.listing %></td>
  <td><%= bid.bidding_price %></td>
  <td><%= bid.chosen_bid %></td>
</tr>
<% end %>
</table>

<br>

<h2>Listings Won</h2>
<br>
<table>
  <tr>
    <th>Listing Name</th>
    <th>Bidding Price</th>
    <th>Paid?</th>
    <th></th>
  </tr>
<% @listings.each do |listing| %>
<tr>
  <td><%= link_to listing.name, listing %></td>
  <td><%= listing.bids.order("bidding_price DESC").first.bidding_price %></td>
  <td><%= listing.paid %></td>
    <% if listing.paid == false %>
  <td><%= link_to "Make Payment", new_listing_braintree_path(listing) %></td>
    <% else %>
  <td></td>
    <% end %>
</tr>
<% end %>
</table>

</div>