config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  resources :users
  resources :listings do
    resources :bids, only: [:create]
    resources :braintree, only: [:new, :create]
  end
  resources :images, only: [:destroy]
  resources :bids, except: [:create]
  get '/search', to: 'listings#search', as: 'search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Auction House</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fresca">
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1OJ2LVjPpwrxpiT1qQNEzrdo40juTQDk&libraries=places" type="text/javascript"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navMain">
              <span class="glyphicon glyphicon-chevron-right" style="color:white;"></span>

            </button>
            <a class="navbar-brand" href="/">Auction House</a>
          </div>
          <ul class="nav navbar-nav">
          </ul>
          <div class="collapse navbar-collapse" id="navMain">
            <ul class="nav navbar-nav pull-right">
              <% if current_user %>
                <% if current_user.role == "admin" %>
                <li>
                  <%= link_to new_listing_path(current_user) do %>
                  Add New Listing
                  <% end %>
                </li>
                <% end %>

                <% if current_user.user? %>
                <li>
                  <%= link_to user_path(current_user) do %>
                  <%= current_user.first_name %>
                  <% end %>
                </li>

                <% else %>
                <li>
                <div class="dropdown">
                  <%= link_to user_path(current_user)  do %>
                  Admin: <%= current_user.first_name %>
                  <% end %>
                  <div id="myDropdown" class="dropdown-content">
                    <%= link_to 'View all Users', users_path %>
                    <%= link_to 'View all Listings', listings_path %>
                  </div>
                </div>
                <% end %>
              </li>
            <li>
              <%= link_to "Logout", '/logout' %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Login', '/login' %>
            </li>
            <li>
            <%= link_to 'Signup', '/signup' %>
            </li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
    <br><br><br>
    <p id="notice"><%= flash[:notice] %></p>
    <%= yield %>
  </body>
</html>